services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack
    ports:
      - "4566:4566"
    environment:
      - SERVICES=s3,ec2,sts,iam
      - DEBUG=0
      - AWS_DEFAULT_REGION=us-east-1
    volumes:
      - "./.localstack:/var/lib/localstack"

  s3-web:
    image: ghcr.io/${OWNER}/s3-web:${TAG}
    container_name: s3-web
    depends_on:
      - localstack
    ports:
      - "3000:3000"
    env_file:
      - ./s3-web/.env